CALL code --install-extension formulahendry.auto-close-tag
CALL code --install-extension formulahendry.auto-rename-tag
CALL code --install-extension abusaidm.html-snippets
CALL code --install-extension hnw.vscode-auto-open-markdown-preview
CALL code --install-extension AlanWalk.markdown-toc
CALL code --install-extension ms-vscode.Theme-MarkdownKit
CALL code --install-extension streetsidesoftware.code-spell-checker
CALL code --install-extension dzannotti.vscode-babel-coloring
CALL code --install-extension msjsdiag.debugger-for-chrome
CALL code --install-extension dbaeumer.vscode-eslint
CALL code --install-extension xabikos.JavaScriptSnippets
CALL code --install-extension leizongmin.node-module-intellisense
CALL code --install-extension streetsidesoftware.code-spell-checker
CALL code --install-extension EQuimper.react-native-react-redux
CALL code --install-extension eg2.tslint
CALL code --install-extension kumar-harsh.graphql-for-vscode
CALL code --install-extension gamunu.vscode-yarn
CALL code --install-extension naumovs.color-highlight
CALL code --install-extension be5invis.vscode-custom-css
CALL code --install-extension EditorConfig.EditorConfig
CALL code --install-extension brpaz.file-templates
CALL code --install-extension spywhere.guides
CALL code --install-extension PKief.material-icon-theme
CALL code --install-extension 2gua.rainbow-brackets
CALL code --install-extension esbenp.prettier-vscode
CALL code --install-extension alefragnani.project-manager
CALL code --install-extension SmukkeKim.theme-setimonokai
CALL code --install-extension WakaTime.vscode-wakatime
code --install-extension Shan.code-settings-sync